import { createHash } from "node:crypto";
import * as lark from "@larksuiteoapi/node-sdk";

import type { GatewayService, InboundMessage } from "../gateway/gateway-service.js";
import type { ApprovalController } from "../approval/approval-controller.js";
import type {
  CardActionEvent,
  MenuEvent,
  SessionController,
} from "../session/session-controller.js";

interface MessageEvent {
  event_id?: string;
  create_time?: string;
  sender: {
    sender_id?: { open_id?: string };
    sender_type: string;
  };
  message: {
    message_id: string;
    root_id?: string;
    create_time: string;
    chat_id: string;
    chat_type: string;
    message_type: string;
    content: string;
  };
}

export class FeishuIngress {
  readonly #gateway: GatewayService;
  readonly #sessions: SessionController;
  readonly #approvals: ApprovalController;
  readonly #dispatcher: lark.EventDispatcher;
  readonly #ws: lark.WSClient;

  constructor(input: {
    appId: string;
    appSecret: string;
    gateway: GatewayService;
    sessions: SessionController;
    approvals: ApprovalController;
    onReady?: () => void;
    onError?: (error: Error) => void;
  }) {
    this.#gateway = input.gateway;
    this.#sessions = input.sessions;
    this.#approvals = input.approvals;
    this.#dispatcher = new lark.EventDispatcher({ loggerLevel: lark.LoggerLevel.warn });
    this.#dispatcher.register({
      "im.message.receive_v1": async (event) => {
        const normalized = normalizeMessageEvent(event as MessageEvent);
        if (normalized) await this.#gateway.handleMessage(normalized);
      },
      "application.bot.menu_v6": async (event) => {
        const normalized = normalizeMenuEvent(event);
        return normalized
          ? this.#sessions.handleMenu(normalized)
          : { toast: { type: "warning", content: "菜单事件格式无效" } };
      },
      "card.action.trigger": async (event: unknown) => {
        const normalized = normalizeCardActionEvent(event);
        if (!normalized) return { toast: { type: "warning", content: "卡片操作格式无效" } };
        return this.#approvals.handleCardAction(normalized) ??
          this.#sessions.handleCardAction(normalized);
      },
      // These delivery receipts are generated by the gateway's own reaction/card
      // activity. Register explicit no-ops so the SDK does not report them as
      // unhandled application events.
      "im.message.message_read_v1": async () => {},
      "im.message.reaction.created_v1": async () => {},
      "im.message.reaction.deleted_v1": async () => {},
    });
    this.#ws = new lark.WSClient({
      appId: input.appId,
      appSecret: input.appSecret,
      domain: lark.Domain.Feishu,
      loggerLevel: lark.LoggerLevel.warn,
      autoReconnect: true,
      handshakeTimeoutMs: 15_000,
      wsConfig: { pingTimeout: 10 },
      ...(input.onReady ? { onReady: input.onReady } : {}),
      ...(input.onError ? { onError: input.onError } : {}),
    });
  }

  start(): Promise<void> {
    return this.#ws.start({ eventDispatcher: this.#dispatcher });
  }

  close(): void {
    this.#ws.close();
  }
}

export function normalizeMenuEvent(raw: unknown): MenuEvent | null {
  const { payload, header } = unwrapV2Event(raw);
  const operator = objectValue(payload.operator);
  const operatorId = stringOrNull(objectValue(operator?.operator_id)?.open_id);
  const eventKey = stringOrNull(payload.event_key);
  if (!operatorId || !eventKey) return null;
  const eventId = interactionEventId(header, payload, `menu:${operatorId}:${eventKey}`);
  return {
    eventId,
    operatorId,
    eventKey,
    receivedAt: eventTime(header, payload),
  };
}

export function normalizeCardActionEvent(raw: unknown): CardActionEvent | null {
  const { payload, header } = unwrapV2Event(raw);
  const context = objectValue(payload.context);
  const operator = objectValue(payload.operator);
  const action = objectValue(payload.action);
  const messageId = stringOrNull(context?.open_message_id ?? payload.open_message_id);
  const chatId = stringOrNull(context?.open_chat_id ?? payload.open_chat_id);
  const operatorId = stringOrNull(operator?.open_id);
  const actionValue = objectValue(action?.value);
  if (!messageId || !chatId || !operatorId || !actionValue) return null;
  const formValue = objectValue(action?.form_value ?? payload.form_value);
  const eventId = interactionEventId(
    header,
    payload,
    `card:${messageId}:${operatorId}:${JSON.stringify(actionValue)}`,
  );
  return {
    eventId,
    messageId,
    chatId,
    operatorId,
    actionValue,
    ...(formValue ? { formValue } : {}),
    receivedAt: eventTime(header, payload),
  };
}

export function normalizeMessageEvent(event: MessageEvent): InboundMessage | null {
  const senderId = event.sender.sender_id?.open_id;
  if (!senderId) return null;
  let content: Record<string, unknown>;
  try {
    content = JSON.parse(event.message.content) as Record<string, unknown>;
  } catch {
    return null;
  }
  let text = "";
  let attachments: InboundMessage["attachments"];
  switch (event.message.message_type) {
    case "text":
      if (typeof content.text !== "string") return null;
      text = content.text;
      break;
    case "image": {
      const fileKey = stringOrNull(content.image_key);
      if (!fileKey) return null;
      attachments = [{ kind: "image", fileKey }];
      break;
    }
    case "file": {
      const fileKey = stringOrNull(content.file_key);
      if (!fileKey) return null;
      const displayName = sanitizeDisplayName(stringOrNull(content.file_name));
      attachments = [{ kind: "file", fileKey, ...(displayName ? { displayName } : {}) }];
      break;
    }
    default:
      return null;
  }
  const chatType = event.message.chat_type;
  if (chatType !== "p2p" && chatType !== "group" && chatType !== "topic") return null;
  const eventId =
    event.event_id ??
    createHash("sha256")
      .update(`${event.message.message_id}:${event.message.create_time}`)
      .digest("hex");
  const receivedAt = Number(event.create_time ?? event.message.create_time);
  return {
    eventId,
    messageId: event.message.message_id,
    chatId: event.message.chat_id,
    chatType,
    senderId,
    text,
    ...(attachments ? { attachments } : {}),
    receivedAt: Number.isFinite(receivedAt) ? receivedAt : Date.now(),
    ...(event.message.root_id ? { rootMessageId: event.message.root_id } : {}),
  };
}

function sanitizeDisplayName(value: string | null): string | null {
  if (!value) return null;
  const leaf = value.replaceAll("\\", "/").split("/").at(-1)?.replace(/[\u0000-\u001f\u007f]/g, "").trim();
  return leaf ? leaf.slice(0, 120) : null;
}

function unwrapV2Event(raw: unknown): {
  payload: Record<string, unknown>;
  header: Record<string, unknown>;
} {
  const outer = objectValue(raw) ?? {};
  return {
    payload: objectValue(outer.event) ?? outer,
    header: objectValue(outer.header) ?? outer,
  };
}

function interactionEventId(
  header: Record<string, unknown>,
  payload: Record<string, unknown>,
  fallback: string,
): string {
  return stringOrNull(header.event_id ?? payload.event_id) ??
    createHash("sha256").update(fallback).digest("hex");
}

function eventTime(header: Record<string, unknown>, payload: Record<string, unknown>): number {
  const value = Number(header.create_time ?? payload.create_time ?? payload.timestamp ?? Date.now());
  return Number.isFinite(value) ? value : Date.now();
}

function objectValue(value: unknown): Record<string, unknown> | null {
  return typeof value === "object" && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function stringOrNull(value: unknown): string | null {
  return typeof value === "string" && value.length > 0 ? value : null;
}
